/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_mi_mp3_util_LameUtil */

#ifndef _Included_com_example_hello_myapplication_utils_LameMp3Util
#define _Included_com_example_hello_myapplication_utils_LameMp3Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hello_myapplication_utils_LameMp3Util
 * Method:    init
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_example_hello_myapplication_utils_LameMp3Util_init
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:    com_example_hello_myapplication_utils_LameMp3Util
 * Method:    encode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_com_example_hello_myapplication_utils_LameMp3Util_encode
  (JNIEnv *, jclass, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     com_example_hello_myapplication_utils_LameMp3Util
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_example_hello_myapplication_utils_LameMp3Util_flush
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_example_hello_myapplication_utils_LameMp3Util
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_hello_myapplication_utils_LameMp3Util_close
  (JNIEnv *, jclass);

/*
 * Class:     com_example_hello_myapplication_utils_LameMp3Util
 * Method:    encodeFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_hello_myapplication_utils_LameMp3Util_encodeFile
  (JNIEnv *, jobject, jstring, jstring);
  
#ifdef __cplusplus
}
#endif
#endif
